<?php

namespace App\Models;

use Carbon\Carbon;
use \DateTimeInterface;
use App\Models\Activebar;
use App\Models\Assignbar;
use App\Models\Interview;
use App\Models\CandidateProfile;
use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Candidate extends Model implements HasMedia
{
    use SoftDeletes;
    use InteractsWithMedia;
    use HasFactory;


    public const TOWN_SELECT = [

        'abc' => 'abc',
    ];

    protected $guarded = ['created_at'];

    public const STATE_SELECT = [

        'New South Wales (NSW)' => 'New South Wales (NSW)',
        'Australian Capital Territory (ACT)' => 'Australian Capital Territory (ACT)',
        'South Australia (SA)' => 'South Australia (SA)',
        'Queensland (QLD)' => 'Queensland (QLD)',
        'Western Australia (WA)' => 'Western Australia (WA)',
        'Victoria (VIC)' => 'Victoria (VIC)',
        'Tasmania (TAS)' => 'Tasmania (TAS)',
        'Northern Territory (NT)' => 'Northern Territory (NT)',
    ];

    public const COUNTRY_SELECT = [
        'Australia ' => 'Australia ',
        'New Zealand' => 'New Zealand',
        'United Kingdom ' => 'United Kingdom ',
        'Austria  ' => 'Austria  ',
        'Belgium' => 'Belgium',
        'Canada ' => 'Canada ',
        'Czech Republic  ' => 'Czech Republic  ',
        'Denmark  ' => 'Denmark  ',
        'Finland  ' => 'Finland  ',
        'France ' => 'France ',
        'Germany  ' => 'Germany  ',
        'Greece' => 'Greece',
        'Iceland ' => 'Iceland ',
        'Israel  ' => 'Israel  ',
        'Italy ' => 'Italy ',
        'Norway ' => 'Norway ',
        'Portugal  ' => 'Portugal  ',
        'Republic of Ireland  ' => 'Republic of Ireland  ',
        'Singapore  ' => 'Singapore  ',
        'Spain ' => 'Spain ',
        'Sweden ' => 'Sweden ',
        'Switzerland ' => 'Switzerland ',
        'The Netherlands ' => 'The Netherlands ',
        'United States of America ' => 'United States of America ',
        'Afghanistan' => 'Afghanistan',
        'Albania' => 'Albania',
        'Algeria' => 'Algeria',
        'Andorra' => 'Andorra',
        'Angola' => 'Angola',
        'Antigua and Barbuda' => 'Antigua and Barbuda',
        'Argentina' => 'Argentina',
        'Armenia' => 'Armenia',
        'Azerbaijan' => 'Azerbaijan',
        'The Bahamas' => 'The Bahamas',
        'Bahrain' => 'Bahrain',
        'Bangladesh' => 'Bangladesh',
        'Barbados' => 'Barbados',
        'Belarus' => 'Belarus',
        'Belize' => 'Belize',
        'Benin' => 'Benin',
        'Bhutan' => 'Bhutan',
        'Bolivia' => 'Bolivia',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
        'Botswana' => 'Botswana',
        'Brazil' => 'Brazil',
        'Brunei' => 'Brunei',
        'Bulgaria' => 'Bulgaria',
        'Burkina Faso' => 'Burkina Faso',
        'Burundi' => 'Burundi',
        'Cambodia' => 'Cambodia',
        'Cameroon' => 'Cameroon',
        'Cape Verde' => 'Cape Verde',
        'Central African Republic' => 'Central African Republic',
        'Chad' => 'Chad',
        'Chile' => 'Chile',
        'China' => 'China',
        'Colombia' => 'Colombia',
        'Comoros' => 'Comoros',
        'Congo, Republic of the' => 'Congo, Republic of the',
        'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
        'Costa Rica' => 'Costa Rica',
        'Cote d-Ivoire' => 'Cote d-Ivoire',
        'Croatia' => 'Croatia',
        'Cuba' => 'Cuba',
        'Cyprus' => 'Cyprus',
        'Djibouti' => 'Djibouti',
        'Dominica' => 'Dominica',
        'Dominican Republic' => 'Dominican Republic',
        'East Timor (Timor-Leste)' => 'East Timor (Timor-Leste)',
        'Ecuador' => 'Ecuador',
        'Egypt' => 'Egypt',
        'El Salvador' => 'El Salvador',
        'Equatorial Guinea' => 'Equatorial Guinea',
        'Eritrea' => 'Eritrea',
        'Estonia' => 'Estonia',
        'Ethiopia' => 'Ethiopia',
        'Fiji' => 'Fiji',
        'Gabon' => 'Gabon',
        'The Gambia' => 'The Gambia',
        'Georgia' => 'Georgia',
        'Ghana' => 'Ghana',
        'Grenada' => 'Grenada',
        'Guatemala' => 'Guatemala',
        'Guinea' => 'Guinea',
        'Guinea-Bissau' => 'Guinea-Bissau',
        'Guyana' => 'Guyana',
        'Haiti' => 'Haiti',
        'Honduras' => 'Honduras',
        'Hungary' => 'Hungary',
        'India' => 'India',
        'Indonesia' => 'Indonesia',
        'Iran' => 'Iran',
        'Iraq' => 'Iraq',
        'Ireland' => 'Ireland',
        'Jamaica' => 'Jamaica',
        'Japan' => 'Japan',
        'Jordan' => 'Jordan',
        'Kazakhstan' => 'Kazakhstan',
        'Kenya' => 'Kenya',
        'Kiribati' => 'Kiribati',
        'Korea, North' => 'Korea, North',
        'Korea, South' => 'Korea, South',
        'Kosovo' => 'Kosovo',
        'Kuwait' => 'Kuwait',
        'Kyrgyzstan' => 'Kyrgyzstan',
        'Laos' => 'Laos',
        'Latvia' => 'Latvia',
        'Lebanon' => 'Lebanon',
        'Lesotho' => 'Lesotho',
        'Liberia' => 'Liberia',
        'Libya' => 'Libya',
        'Liechtenstein' => 'Liechtenstein',
        'Lithuania' => 'Lithuania',
        'Luxembourg' => 'Luxembourg',
        'Macedonia' => 'Macedonia',
        'Madagascar' => 'Madagascar',
        'Malawi' => 'Malawi',
        'Malaysia' => 'Malaysia',
        'Maldives' => 'Maldives',
        'Mali' => 'Mali',
        'Malta' => 'Malta',
        'Marshall Islands' => 'Marshall Islands',
        'Mauritania' => 'Mauritania',
        'Mauritius' => 'Mauritius',
        'Mexico' => 'Mexico',
        'Micronesia, Federated States of' => 'Micronesia, Federated States of',
        'Moldova' => 'Moldova',
        'Monaco' => 'Monaco',
        'Mongolia' => 'Mongolia',
        'Montenegro' => 'Montenegro',
        'Morocco' => 'Morocco',
        'Mozambique' => 'Mozambique',
        'Myanmar (Burma)' => 'Myanmar (Burma)',
        'Namibia' => 'Namibia',
        'Nauru' => 'Nauru',
        'Nepal' => 'Nepal',
        'Nicaragua' => 'Nicaragua',
        'Niger' => 'Niger',
        'Nigeria' => 'Nigeria',
        'Oman' => 'Oman',
        'Pakistan' => 'Pakistan',
        'Palau' => 'Palau',
        'Panama' => 'Panama',
        'Papua New Guinea' => 'Papua New Guinea',
        'Paraguay' => 'Paraguay',
        'Peru' => 'Peru',
        'Philippines' => 'Philippines',
        'Poland' => 'Poland',
        'Qatar' => 'Qatar',
        'Romania' => 'Romania',
        'Russia' => 'Russia',
        'Rwanda' => 'Rwanda',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
        'Saint Lucia' => 'Saint Lucia',
        'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
        'Samoa' => 'Samoa',
        'San Marino' => 'San Marino',
        'Sao Tome and Principe' => 'Sao Tome and Principe',
        'Saudi Arabia' => 'Saudi Arabia',
        'Senegal' => 'Senegal',
        'Serbia' => 'Serbia',
        'Seychelles' => 'Seychelles',
        'Sierra Leone' => 'Sierra Leone',
        'Slovakia' => 'Slovakia',
        'Slovenia' => 'Slovenia',
        'Solomon Islands' => 'Solomon Islands',
        'Somalia' => 'Somalia',
        'South Africa' => 'South Africa',
        'South Sudan' => 'South Sudan',
        'Sri Lanka' => 'Sri Lanka',
        'Sudan' => 'Sudan',
        'Suriname' => 'Suriname',
        'Swaziland' => 'Swaziland',
        'Syria' => 'Syria',
        'Taiwan' => 'Taiwan',
        'Tajikistan' => 'Tajikistan',
        'Tanzania' => 'Tanzania',
        'Thailand' => 'Thailand',
        'Togo' => 'Togo',
        'Tonga' => 'Tonga',
        'Trinidad and Tobago' => 'Trinidad and Tobago',
        'Tunisia' => 'Tunisia',
        'Turkey' => 'Turkey',
        'Turkmenistan' => 'Turkmenistan',
        'Tuvalu' => 'Tuvalu',
        'Uganda' => 'Uganda',
        'Ukraine' => 'Ukraine',
        'United Arab Emirates' => 'United Arab Emirates',
        'Uruguay' => 'Uruguay',
        'Uzbekistan' => 'Uzbekistan',
        'Vanuatu' => 'Vanuatu',
        'Vatican City (Holy See)' => 'Vatican City (Holy See)',
        'Venezuela' => 'Venezuela',
        'Vietnam' => 'Vietnam',
        'Yemen' => 'Yemen',
        'Zambia' => 'Zambia',
        'Zimbabwe' => 'Zimbabwe',



    ];

    public const DEVISION_SELECT = [

        'General Practitioners ' => 'General Practitioners ',
        'Healthcare Executives ' => 'Healthcare Executives ',
        'Hospital Doctors' => 'Hospital Doctors',
        'Locum Doctors' => 'Locum Doctors',
        'Nurses & Carers' => 'Nurses & Carers',
        'Allergologist' => 'Allergologist',
        'Arts Therapist ' => 'Arts Therapist ',
        'Audiologist' => 'Audiologist',
        'Chiropractor ' => 'Chiropractor ',
        'Dietitians ' => 'Dietitians ',
        'Exercise Physiologist ' => 'Exercise Physiologist ',
        'Genetic Counsellor' => 'Genetic Counsellor',
        'Medical Radiologist ' => 'Medical Radiologist ',
        'Music Therapist' => 'Music Therapist',
        'Occupational Therapist' => 'Occupational Therapist',
        'Optometrist' => 'Optometrist',
        'Orthotist and prosthetist' => 'Orthotist and prosthetist',
        'Osteopathist ' => 'Osteopathist ',
        'Perfusionist ' => 'Perfusionist ',
        'Physiotherapist' => 'Physiotherapist',
        'Podiatrist' => 'Podiatrist',
        'Psychologist' => 'Psychologist',
        'Psychology & Mental health' => 'Psychology & Mental health',
        'Rehabilitation Counsellor ' => 'Rehabilitation Counsellor ',
        'Sonographer' => 'Sonographer',
        'Specialist service' => 'Specialist service',
        'Speech-pathology' => 'Speech-pathology',
        'Midwife' => 'Midwife',
        'Dentists' => 'Dentists',



    ];

    public const DISTRICT_SELECT = [

        'abc' => 'abc',
    ];

    public const SENORITY_SELECT = [

        'Internship - PGY Year 1 ' => 'Internship - PGY Year 1 ',
        'Junior House Officer - PGY Year 2 ' => 'Junior House Officer - PGY Year 2 ',
        'Senior House Officer - PGY Year 3 ' => 'Senior House Officer - PGY Year 3 ',
        'Principal Health Officer – PGY Year 4 ' => 'Principal Health Officer – PGY Year 4 ',
        'Registrars' => 'Registrars',
        'Consultant' => 'Consultant',
    ];

    public const VISA_TYPE_SELECT = [
        'Visitor visas' => 'Visitor visas',
        'Studying and training visas' => 'Studying and training visas',
        'Family and partner visas' => 'Family and partner visas',
        'Working and skilled visas' => 'Working and skilled visas',
        'Refugee and humanitarian visas' => 'Refugee and humanitarian visas',
        'Other visas' => 'Other visas',
        'Repealed visas' => 'Repealed visas',
    ];

    public const SPECIALTY_SELECT = [

        'Anaesthetics' => 'Anaesthetics',
        'Emergency Medicine ' => 'Emergency Medicine ',
        'General Practice ' => 'General Practice ',
        'Gastroenterologist' => 'Gastroenterologist',
        'Intensive care ' => 'Intensive care ',
        'Medicine' => 'Medicine',
        'Obtetrics & Gynaecology ' => 'Obtetrics & Gynaecology ',
        'Pathologist' => 'Pathologist',
        'Peadiatrics' => 'Peadiatrics',
        'Psychiatry ' => 'Psychiatry ',
        'Radiology' => 'Radiology',
        'Surgery ' => 'Surgery ',
    ];

    public const MAIN_CITY_SELECT = [
        'Sydney' => 'Sydney',
        'Coffs Harbour' => 'Coffs Harbour',
        'Sunshine Coast' => 'Sunshine Coast',
        'Central Coast' => 'Central Coast',
        'Cairns' => 'Cairns',
        'Townsville' => 'Townsville',
        'Ipswich' => 'Ipswich',
        'Penrith' => 'Penrith',
        'New Castle' => 'New Castle',
        'Hervey Bay' => 'Hervey Bay',
        'Geelong' => 'Geelong',
        'Dubbo' => 'Dubbo',
        'Liverpool' => 'Liverpool',
        'Ballarat' => 'Ballarat',
        'Blue Mountains' => 'Blue Mountains',
        'Canberra' => 'Canberra',
        'Hobart' => 'Hobart',
        'Launceston' => 'Launceston',
        'Bundaberg' => 'Bundaberg',
        'Albury' => 'Albury',
        'Wangaratta ' => 'Wangaratta ',
        'Wollongong ' => 'Wollongong ',
        'Bendigo' => 'Bendigo',
        'Grafton' => 'Grafton',
        'Mackay' => 'Mackay',
        'Darwin' => 'Darwin',
        'Bunbury ' => 'Bunbury ',
        'Gladstone ' => 'Gladstone ',
        'Wagga Wagga ' => 'Wagga Wagga ',
        'Toowoomba ' => 'Toowoomba ',
        'Lismore ' => 'Lismore ',
        'Campbelltown ' => 'Campbelltown ',
        'Orange' => 'Orange',
        'Tamworth ' => 'Tamworth ',
        'Byron bay ' => 'Byron bay ',
        'Port Macquaire' => 'Port Macquaire',
        'Hills District Suburbs ' => 'Hills District Suburbs ',
        'Bathurst' => 'Bathurst',
        'Goulbun' => 'Goulbun',
        'Shepparton' => 'Shepparton',
        'Mildura' => 'Mildura',
        'Katherine ' => 'Katherine ',
        'South West ' => 'South West ',
        'North West ' => 'North West ',
        'Central West' => 'Central West',
        'Busselton' => 'Busselton',
        'Gold Coast - North' => 'Gold Coast - North',
        'Gold Coast - South' => 'Gold Coast - South',
        'North Adelaide' => 'North Adelaide',
        'South Adelaide' => 'South Adelaide',
        'Warragul ' => 'Warragul ',
        'Sale' => 'Sale',
        'Bairnsdale ' => 'Bairnsdale ',
        'Philip Island ' => 'Philip Island ',
        'Moe' => 'Moe',
        'Mornington Penninsula' => 'Mornington Penninsula',
        'Kalgoorlie ' => 'Kalgoorlie ',
        'Geraldton ' => 'Geraldton ',
        'Moonee' => 'Moonee',
        'Morwell' => 'Morwell',
        'San Jose' => 'San Jose',
        'East Perth ' => 'East Perth ',
        'Brisbane South ' => 'Brisbane South ',
        'Rutherford ' => 'Rutherford ',
        'Eastern Melbour ' => 'Eastern Melbour ',
        'Yarra' => 'Yarra',
        'Port Pirie ' => 'Port Pirie ',
        'Port Lincoln ' => 'Port Lincoln ',
        'Devonport ' => 'Devonport ',
        'Alice Springs' => 'Alice Springs',

    ];

    public const GRADUATION_SELECT = [

        'Local Graduate' => 'Local Graduate',
        'Overseas Graduate' => 'Overseas Graduate',
    ];

    public const PROFESSION_SELECT = [

        'Doctor' => 'Doctor',
        'Nurse' => 'Nurse',
        'Allied Health Professionals' => 'Allied Health Professionals',
        'Healthcare Executives' => 'Healthcare Executives',
        'Dentists' => 'Dentists',
    ];

    public const LICENSE_TYPE_SELECT = [
        'Eligible for General Registration ' => 'Eligible for General Registration ',
        'Eligible for Limited Registration ' => 'Eligible for Limited Registration ',
        'Eligible for Provisional Registration ' => 'Eligible for Provisional Registration ',
        'General' => 'General',
        'Limited' => 'Limited',
        'Non-Practising Registration ' => 'Non-Practising Registration ',
        'Not Applicable' => 'Not Applicable',
        'Provisional' => 'Provisional',
        'Specialist' => 'Specialist',
        'Student' => 'Student',
    ];

    public const PROFESSION_LOGIN_SELECT = [
        'Doctor' => 'Doctor',
        'Nurse' => 'Nurse',
        'Allied Health Professionals' => 'Allied Health Professionals',
        'Healthcare Executives' => 'Healthcare Executives',
    ];

    public const PRACTICE_COUNTRY_SELECT = [

        'Australia ' => 'Australia ',
        'New Zealand' => 'New Zealand',
        'United Kingdom ' => 'United Kingdom ',
        'Austria  ' => 'Austria  ',
        'Belgium' => 'Belgium',
        'Canada ' => 'Canada ',
        'Czech Republic  ' => 'Czech Republic  ',
        'Denmark  ' => 'Denmark  ',
        'Finland  ' => 'Finland  ',
        'France ' => 'France ',
        'Germany  ' => 'Germany  ',
        'Greece' => 'Greece',
        'Iceland ' => 'Iceland ',
        'Israel  ' => 'Israel  ',
        'Italy ' => 'Italy ',
        'Norway ' => 'Norway ',
        'Portugal  ' => 'Portugal  ',
        'Republic of Ireland  ' => 'Republic of Ireland  ',
        'Singapore  ' => 'Singapore  ',
        'Spain ' => 'Spain ',
        'Sweden ' => 'Sweden ',
        'Switzerland ' => 'Switzerland ',
        'The Netherlands ' => 'The Netherlands ',
        'United States of America ' => 'United States of America ',
        'Afghanistan' => 'Afghanistan',
        'Albania' => 'Albania',
        'Algeria' => 'Algeria',
        'Andorra' => 'Andorra',
        'Angola' => 'Angola',
        'Antigua and Barbuda' => 'Antigua and Barbuda',
        'Argentina' => 'Argentina',
        'Armenia' => 'Armenia',
        'Azerbaijan' => 'Azerbaijan',
        'The Bahamas' => 'The Bahamas',
        'Bahrain' => 'Bahrain',
        'Bangladesh' => 'Bangladesh',
        'Barbados' => 'Barbados',
        'Belarus' => 'Belarus',
        'Belize' => 'Belize',
        'Benin' => 'Benin',
        'Bhutan' => 'Bhutan',
        'Bolivia' => 'Bolivia',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
        'Botswana' => 'Botswana',
        'Brazil' => 'Brazil',
        'Brunei' => 'Brunei',
        'Bulgaria' => 'Bulgaria',
        'Burkina Faso' => 'Burkina Faso',
        'Burundi' => 'Burundi',
        'Cambodia' => 'Cambodia',
        'Cameroon' => 'Cameroon',
        'Cape Verde' => 'Cape Verde',
        'Central African Republic' => 'Central African Republic',
        'Chad' => 'Chad',
        'Chile' => 'Chile',
        'China' => 'China',
        'Colombia' => 'Colombia',
        'Comoros' => 'Comoros',
        'Congo, Republic of the' => 'Congo, Republic of the',
        'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
        'Costa Rica' => 'Costa Rica',
        'Cote d-Ivoire' => 'Cote d-Ivoire',
        'Croatia' => 'Croatia',
        'Cuba' => 'Cuba',
        'Cyprus' => 'Cyprus',
        'Djibouti' => 'Djibouti',
        'Dominica' => 'Dominica',
        'Dominican Republic' => 'Dominican Republic',
        'East Timor (Timor-Leste)' => 'East Timor (Timor-Leste)',
        'Ecuador' => 'Ecuador',
        'Egypt' => 'Egypt',
        'El Salvador' => 'El Salvador',
        'Equatorial Guinea' => 'Equatorial Guinea',
        'Eritrea' => 'Eritrea',
        'Estonia' => 'Estonia',
        'Ethiopia' => 'Ethiopia',
        'Fiji' => 'Fiji',
        'Gabon' => 'Gabon',
        'The Gambia' => 'The Gambia',
        'Georgia' => 'Georgia',
        'Ghana' => 'Ghana',
        'Grenada' => 'Grenada',
        'Guatemala' => 'Guatemala',
        'Guinea' => 'Guinea',
        'Guinea-Bissau' => 'Guinea-Bissau',
        'Guyana' => 'Guyana',
        'Haiti' => 'Haiti',
        'Honduras' => 'Honduras',
        'Hungary' => 'Hungary',
        'India' => 'India',
        'Indonesia' => 'Indonesia',
        'Iran' => 'Iran',
        'Iraq' => 'Iraq',
        'Ireland' => 'Ireland',
        'Jamaica' => 'Jamaica',
        'Japan' => 'Japan',
        'Jordan' => 'Jordan',
        'Kazakhstan' => 'Kazakhstan',
        'Kenya' => 'Kenya',
        'Kiribati' => 'Kiribati',
        'Korea, North' => 'Korea, North',
        'Korea, South' => 'Korea, South',
        'Kosovo' => 'Kosovo',
        'Kuwait' => 'Kuwait',
        'Kyrgyzstan' => 'Kyrgyzstan',
        'Laos' => 'Laos',
        'Latvia' => 'Latvia',
        'Lebanon' => 'Lebanon',
        'Lesotho' => 'Lesotho',
        'Liberia' => 'Liberia',
        'Libya' => 'Libya',
        'Liechtenstein' => 'Liechtenstein',
        'Lithuania' => 'Lithuania',
        'Luxembourg' => 'Luxembourg',
        'Macedonia' => 'Macedonia',
        'Madagascar' => 'Madagascar',
        'Malawi' => 'Malawi',
        'Malaysia' => 'Malaysia',
        'Maldives' => 'Maldives',
        'Mali' => 'Mali',
        'Malta' => 'Malta',
        'Marshall Islands' => 'Marshall Islands',
        'Mauritania' => 'Mauritania',
        'Mauritius' => 'Mauritius',
        'Mexico' => 'Mexico',
        'Micronesia, Federated States of' => 'Micronesia, Federated States of',
        'Moldova' => 'Moldova',
        'Monaco' => 'Monaco',
        'Mongolia' => 'Mongolia',
        'Montenegro' => 'Montenegro',
        'Morocco' => 'Morocco',
        'Mozambique' => 'Mozambique',
        'Myanmar (Burma)' => 'Myanmar (Burma)',
        'Namibia' => 'Namibia',
        'Nauru' => 'Nauru',
        'Nepal' => 'Nepal',
        'Nicaragua' => 'Nicaragua',
        'Niger' => 'Niger',
        'Nigeria' => 'Nigeria',
        'Oman' => 'Oman',
        'Pakistan' => 'Pakistan',
        'Palau' => 'Palau',
        'Panama' => 'Panama',
        'Papua New Guinea' => 'Papua New Guinea',
        'Paraguay' => 'Paraguay',
        'Peru' => 'Peru',
        'Philippines' => 'Philippines',
        'Poland' => 'Poland',
        'Qatar' => 'Qatar',
        'Romania' => 'Romania',
        'Russia' => 'Russia',
        'Rwanda' => 'Rwanda',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
        'Saint Lucia' => 'Saint Lucia',
        'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
        'Samoa' => 'Samoa',
        'San Marino' => 'San Marino',
        'Sao Tome and Principe' => 'Sao Tome and Principe',
        'Saudi Arabia' => 'Saudi Arabia',
        'Senegal' => 'Senegal',
        'Serbia' => 'Serbia',
        'Seychelles' => 'Seychelles',
        'Sierra Leone' => 'Sierra Leone',
        'Slovakia' => 'Slovakia',
        'Slovenia' => 'Slovenia',
        'Solomon Islands' => 'Solomon Islands',
        'Somalia' => 'Somalia',
        'South Africa' => 'South Africa',
        'South Sudan' => 'South Sudan',
        'Sri Lanka' => 'Sri Lanka',
        'Sudan' => 'Sudan',
        'Suriname' => 'Suriname',
        'Swaziland' => 'Swaziland',
        'Syria' => 'Syria',
        'Taiwan' => 'Taiwan',
        'Tajikistan' => 'Tajikistan',
        'Tanzania' => 'Tanzania',
        'Thailand' => 'Thailand',
        'Togo' => 'Togo',
        'Tonga' => 'Tonga',
        'Trinidad and Tobago' => 'Trinidad and Tobago',
        'Tunisia' => 'Tunisia',
        'Turkey' => 'Turkey',
        'Turkmenistan' => 'Turkmenistan',
        'Tuvalu' => 'Tuvalu',
        'Uganda' => 'Uganda',
        'Ukraine' => 'Ukraine',
        'United Arab Emirates' => 'United Arab Emirates',
        'Uruguay' => 'Uruguay',
        'Uzbekistan' => 'Uzbekistan',
        'Vanuatu' => 'Vanuatu',
        'Vatican City (Holy See)' => 'Vatican City (Holy See)',
        'Venezuela' => 'Venezuela',
        'Vietnam' => 'Vietnam',
        'Yemen' => 'Yemen',
        'Zambia' => 'Zambia',
        'Zimbabwe' => 'Zimbabwe',
    ];

    public const WORK_RIGHTS_STATUS_SELECT = [
        'No Limits' => 'No Limits',
        'Limited Working Hours' => 'Limited Working Hours',
        'No Working Rights' => 'No Working Rights',

    ];

    public const COUNTRY_OF_RESIDENCE_SELECT = [
        'Australia ' => 'Australia ',
        'New Zealand' => 'New Zealand',
        'United Kingdom ' => 'United Kingdom ',
        'Austria  ' => 'Austria  ',
        'Belgium' => 'Belgium',
        'Canada ' => 'Canada ',
        'Czech Republic  ' => 'Czech Republic  ',
        'Denmark  ' => 'Denmark  ',
        'Finland  ' => 'Finland  ',
        'France ' => 'France ',
        'Germany  ' => 'Germany  ',
        'Greece' => 'Greece',
        'Iceland ' => 'Iceland ',
        'Israel  ' => 'Israel  ',
        'Italy ' => 'Italy ',
        'Norway ' => 'Norway ',
        'Portugal  ' => 'Portugal  ',
        'Republic of Ireland  ' => 'Republic of Ireland  ',
        'Singapore  ' => 'Singapore  ',
        'Spain ' => 'Spain ',
        'Sweden ' => 'Sweden ',
        'Switzerland ' => 'Switzerland ',
        'The Netherlands ' => 'The Netherlands ',
        'United States of America ' => 'United States of America ',
        'Afghanistan' => 'Afghanistan',
        'Albania' => 'Albania',
        'Algeria' => 'Algeria',
        'Andorra' => 'Andorra',
        'Angola' => 'Angola',
        'Antigua and Barbuda' => 'Antigua and Barbuda',
        'Argentina' => 'Argentina',
        'Armenia' => 'Armenia',
        'Azerbaijan' => 'Azerbaijan',
        'The Bahamas' => 'The Bahamas',
        'Bahrain' => 'Bahrain',
        'Bangladesh' => 'Bangladesh',
        'Barbados' => 'Barbados',
        'Belarus' => 'Belarus',
        'Belize' => 'Belize',
        'Benin' => 'Benin',
        'Bhutan' => 'Bhutan',
        'Bolivia' => 'Bolivia',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
        'Botswana' => 'Botswana',
        'Brazil' => 'Brazil',
        'Brunei' => 'Brunei',
        'Bulgaria' => 'Bulgaria',
        'Burkina Faso' => 'Burkina Faso',
        'Burundi' => 'Burundi',
        'Cambodia' => 'Cambodia',
        'Cameroon' => 'Cameroon',
        'Cape Verde' => 'Cape Verde',
        'Central African Republic' => 'Central African Republic',
        'Chad' => 'Chad',
        'Chile' => 'Chile',
        'China' => 'China',
        'Colombia' => 'Colombia',
        'Comoros' => 'Comoros',
        'Congo, Republic of the' => 'Congo, Republic of the',
        'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
        'Costa Rica' => 'Costa Rica',
        'Cote d-Ivoire' => 'Cote d-Ivoire',
        'Croatia' => 'Croatia',
        'Cuba' => 'Cuba',
        'Cyprus' => 'Cyprus',
        'Djibouti' => 'Djibouti',
        'Dominica' => 'Dominica',
        'Dominican Republic' => 'Dominican Republic',
        'East Timor (Timor-Leste)' => 'East Timor (Timor-Leste)',
        'Ecuador' => 'Ecuador',
        'Egypt' => 'Egypt',
        'El Salvador' => 'El Salvador',
        'Equatorial Guinea' => 'Equatorial Guinea',
        'Eritrea' => 'Eritrea',
        'Estonia' => 'Estonia',
        'Ethiopia' => 'Ethiopia',
        'Fiji' => 'Fiji',
        'Gabon' => 'Gabon',
        'The Gambia' => 'The Gambia',
        'Georgia' => 'Georgia',
        'Ghana' => 'Ghana',
        'Grenada' => 'Grenada',
        'Guatemala' => 'Guatemala',
        'Guinea' => 'Guinea',
        'Guinea-Bissau' => 'Guinea-Bissau',
        'Guyana' => 'Guyana',
        'Haiti' => 'Haiti',
        'Honduras' => 'Honduras',
        'Hungary' => 'Hungary',
        'India' => 'India',
        'Indonesia' => 'Indonesia',
        'Iran' => 'Iran',
        'Iraq' => 'Iraq',
        'Ireland' => 'Ireland',
        'Jamaica' => 'Jamaica',
        'Japan' => 'Japan',
        'Jordan' => 'Jordan',
        'Kazakhstan' => 'Kazakhstan',
        'Kenya' => 'Kenya',
        'Kiribati' => 'Kiribati',
        'Korea, North' => 'Korea, North',
        'Korea, South' => 'Korea, South',
        'Kosovo' => 'Kosovo',
        'Kuwait' => 'Kuwait',
        'Kyrgyzstan' => 'Kyrgyzstan',
        'Laos' => 'Laos',
        'Latvia' => 'Latvia',
        'Lebanon' => 'Lebanon',
        'Lesotho' => 'Lesotho',
        'Liberia' => 'Liberia',
        'Libya' => 'Libya',
        'Liechtenstein' => 'Liechtenstein',
        'Lithuania' => 'Lithuania',
        'Luxembourg' => 'Luxembourg',
        'Macedonia' => 'Macedonia',
        'Madagascar' => 'Madagascar',
        'Malawi' => 'Malawi',
        'Malaysia' => 'Malaysia',
        'Maldives' => 'Maldives',
        'Mali' => 'Mali',
        'Malta' => 'Malta',
        'Marshall Islands' => 'Marshall Islands',
        'Mauritania' => 'Mauritania',
        'Mauritius' => 'Mauritius',
        'Mexico' => 'Mexico',
        'Micronesia, Federated States of' => 'Micronesia, Federated States of',
        'Moldova' => 'Moldova',
        'Monaco' => 'Monaco',
        'Mongolia' => 'Mongolia',
        'Montenegro' => 'Montenegro',
        'Morocco' => 'Morocco',
        'Mozambique' => 'Mozambique',
        'Myanmar (Burma)' => 'Myanmar (Burma)',
        'Namibia' => 'Namibia',
        'Nauru' => 'Nauru',
        'Nepal' => 'Nepal',
        'Nicaragua' => 'Nicaragua',
        'Niger' => 'Niger',
        'Nigeria' => 'Nigeria',
        'Oman' => 'Oman',
        'Pakistan' => 'Pakistan',
        'Palau' => 'Palau',
        'Panama' => 'Panama',
        'Papua New Guinea' => 'Papua New Guinea',
        'Paraguay' => 'Paraguay',
        'Peru' => 'Peru',
        'Philippines' => 'Philippines',
        'Poland' => 'Poland',
        'Qatar' => 'Qatar',
        'Romania' => 'Romania',
        'Russia' => 'Russia',
        'Rwanda' => 'Rwanda',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
        'Saint Lucia' => 'Saint Lucia',
        'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
        'Samoa' => 'Samoa',
        'San Marino' => 'San Marino',
        'Sao Tome and Principe' => 'Sao Tome and Principe',
        'Saudi Arabia' => 'Saudi Arabia',
        'Senegal' => 'Senegal',
        'Serbia' => 'Serbia',
        'Seychelles' => 'Seychelles',
        'Sierra Leone' => 'Sierra Leone',
        'Slovakia' => 'Slovakia',
        'Slovenia' => 'Slovenia',
        'Solomon Islands' => 'Solomon Islands',
        'Somalia' => 'Somalia',
        'South Africa' => 'South Africa',
        'South Sudan' => 'South Sudan',
        'Sri Lanka' => 'Sri Lanka',
        'Sudan' => 'Sudan',
        'Suriname' => 'Suriname',
        'Swaziland' => 'Swaziland',
        'Syria' => 'Syria',
        'Taiwan' => 'Taiwan',
        'Tajikistan' => 'Tajikistan',
        'Tanzania' => 'Tanzania',
        'Thailand' => 'Thailand',
        'Togo' => 'Togo',
        'Tonga' => 'Tonga',
        'Trinidad and Tobago' => 'Trinidad and Tobago',
        'Tunisia' => 'Tunisia',
        'Turkey' => 'Turkey',
        'Turkmenistan' => 'Turkmenistan',
        'Tuvalu' => 'Tuvalu',
        'Uganda' => 'Uganda',
        'Ukraine' => 'Ukraine',
        'United Arab Emirates' => 'United Arab Emirates',
        'Uruguay' => 'Uruguay',
        'Uzbekistan' => 'Uzbekistan',
        'Vanuatu' => 'Vanuatu',
        'Vatican City (Holy See)' => 'Vatican City (Holy See)',
        'Venezuela' => 'Venezuela',
        'Vietnam' => 'Vietnam',
        'Yemen' => 'Yemen',
        'Zambia' => 'Zambia',
        'Zimbabwe' => 'Zimbabwe',
    ];

    public const EXPERIENCE_FROM_HOME_SELECT = [
        '1-3' => '1-3',
        '3-5' => '3-5',
        '5-10' => '5-10',
        'Above 10' => 'Above 10',
    ];

    public const COUNTRY_OF_CITIZENSHIP_SELECT = [
        'Australia ' => 'Australia ',
        'New Zealand' => 'New Zealand',
        'United Kingdom ' => 'United Kingdom ',
        'Austria  ' => 'Austria  ',
        'Belgium' => 'Belgium',
        'Canada ' => 'Canada ',
        'Czech Republic  ' => 'Czech Republic  ',
        'Denmark  ' => 'Denmark  ',
        'Finland  ' => 'Finland  ',
        'France ' => 'France ',
        'Germany  ' => 'Germany  ',
        'Greece' => 'Greece',
        'Iceland ' => 'Iceland ',
        'Israel  ' => 'Israel  ',
        'Italy ' => 'Italy ',
        'Norway ' => 'Norway ',
        'Portugal  ' => 'Portugal  ',
        'Republic of Ireland  ' => 'Republic of Ireland  ',
        'Singapore  ' => 'Singapore  ',
        'Spain ' => 'Spain ',
        'Sweden ' => 'Sweden ',
        'Switzerland ' => 'Switzerland ',
        'The Netherlands ' => 'The Netherlands ',
        'United States of America ' => 'United States of America ',
        'Afghanistan' => 'Afghanistan',
        'Albania' => 'Albania',
        'Algeria' => 'Algeria',
        'Andorra' => 'Andorra',
        'Angola' => 'Angola',
        'Antigua and Barbuda' => 'Antigua and Barbuda',
        'Argentina' => 'Argentina',
        'Armenia' => 'Armenia',
        'Azerbaijan' => 'Azerbaijan',
        'The Bahamas' => 'The Bahamas',
        'Bahrain' => 'Bahrain',
        'Bangladesh' => 'Bangladesh',
        'Barbados' => 'Barbados',
        'Belarus' => 'Belarus',
        'Belize' => 'Belize',
        'Benin' => 'Benin',
        'Bhutan' => 'Bhutan',
        'Bolivia' => 'Bolivia',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
        'Botswana' => 'Botswana',
        'Brazil' => 'Brazil',
        'Brunei' => 'Brunei',
        'Bulgaria' => 'Bulgaria',
        'Burkina Faso' => 'Burkina Faso',
        'Burundi' => 'Burundi',
        'Cambodia' => 'Cambodia',
        'Cameroon' => 'Cameroon',
        'Cape Verde' => 'Cape Verde',
        'Central African Republic' => 'Central African Republic',
        'Chad' => 'Chad',
        'Chile' => 'Chile',
        'China' => 'China',
        'Colombia' => 'Colombia',
        'Comoros' => 'Comoros',
        'Congo, Republic of the' => 'Congo, Republic of the',
        'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
        'Costa Rica' => 'Costa Rica',
        'Cote d-Ivoire' => 'Cote d-Ivoire',
        'Croatia' => 'Croatia',
        'Cuba' => 'Cuba',
        'Cyprus' => 'Cyprus',
        'Djibouti' => 'Djibouti',
        'Dominica' => 'Dominica',
        'Dominican Republic' => 'Dominican Republic',
        'East Timor (Timor-Leste)' => 'East Timor (Timor-Leste)',
        'Ecuador' => 'Ecuador',
        'Egypt' => 'Egypt',
        'El Salvador' => 'El Salvador',
        'Equatorial Guinea' => 'Equatorial Guinea',
        'Eritrea' => 'Eritrea',
        'Estonia' => 'Estonia',
        'Ethiopia' => 'Ethiopia',
        'Fiji' => 'Fiji',
        'Gabon' => 'Gabon',
        'The Gambia' => 'The Gambia',
        'Georgia' => 'Georgia',
        'Ghana' => 'Ghana',
        'Grenada' => 'Grenada',
        'Guatemala' => 'Guatemala',
        'Guinea' => 'Guinea',
        'Guinea-Bissau' => 'Guinea-Bissau',
        'Guyana' => 'Guyana',
        'Haiti' => 'Haiti',
        'Honduras' => 'Honduras',
        'Hungary' => 'Hungary',
        'India' => 'India',
        'Indonesia' => 'Indonesia',
        'Iran' => 'Iran',
        'Iraq' => 'Iraq',
        'Ireland' => 'Ireland',
        'Jamaica' => 'Jamaica',
        'Japan' => 'Japan',
        'Jordan' => 'Jordan',
        'Kazakhstan' => 'Kazakhstan',
        'Kenya' => 'Kenya',
        'Kiribati' => 'Kiribati',
        'Korea, North' => 'Korea, North',
        'Korea, South' => 'Korea, South',
        'Kosovo' => 'Kosovo',
        'Kuwait' => 'Kuwait',
        'Kyrgyzstan' => 'Kyrgyzstan',
        'Laos' => 'Laos',
        'Latvia' => 'Latvia',
        'Lebanon' => 'Lebanon',
        'Lesotho' => 'Lesotho',
        'Liberia' => 'Liberia',
        'Libya' => 'Libya',
        'Liechtenstein' => 'Liechtenstein',
        'Lithuania' => 'Lithuania',
        'Luxembourg' => 'Luxembourg',
        'Macedonia' => 'Macedonia',
        'Madagascar' => 'Madagascar',
        'Malawi' => 'Malawi',
        'Malaysia' => 'Malaysia',
        'Maldives' => 'Maldives',
        'Mali' => 'Mali',
        'Malta' => 'Malta',
        'Marshall Islands' => 'Marshall Islands',
        'Mauritania' => 'Mauritania',
        'Mauritius' => 'Mauritius',
        'Mexico' => 'Mexico',
        'Micronesia, Federated States of' => 'Micronesia, Federated States of',
        'Moldova' => 'Moldova',
        'Monaco' => 'Monaco',
        'Mongolia' => 'Mongolia',
        'Montenegro' => 'Montenegro',
        'Morocco' => 'Morocco',
        'Mozambique' => 'Mozambique',
        'Myanmar (Burma)' => 'Myanmar (Burma)',
        'Namibia' => 'Namibia',
        'Nauru' => 'Nauru',
        'Nepal' => 'Nepal',
        'Nicaragua' => 'Nicaragua',
        'Niger' => 'Niger',
        'Nigeria' => 'Nigeria',
        'Oman' => 'Oman',
        'Pakistan' => 'Pakistan',
        'Palau' => 'Palau',
        'Panama' => 'Panama',
        'Papua New Guinea' => 'Papua New Guinea',
        'Paraguay' => 'Paraguay',
        'Peru' => 'Peru',
        'Philippines' => 'Philippines',
        'Poland' => 'Poland',
        'Qatar' => 'Qatar',
        'Romania' => 'Romania',
        'Russia' => 'Russia',
        'Rwanda' => 'Rwanda',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
        'Saint Lucia' => 'Saint Lucia',
        'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
        'Samoa' => 'Samoa',
        'San Marino' => 'San Marino',
        'Sao Tome and Principe' => 'Sao Tome and Principe',
        'Saudi Arabia' => 'Saudi Arabia',
        'Senegal' => 'Senegal',
        'Serbia' => 'Serbia',
        'Seychelles' => 'Seychelles',
        'Sierra Leone' => 'Sierra Leone',
        'Slovakia' => 'Slovakia',
        'Slovenia' => 'Slovenia',
        'Solomon Islands' => 'Solomon Islands',
        'Somalia' => 'Somalia',
        'South Africa' => 'South Africa',
        'South Sudan' => 'South Sudan',
        'Sri Lanka' => 'Sri Lanka',
        'Sudan' => 'Sudan',
        'Suriname' => 'Suriname',
        'Swaziland' => 'Swaziland',
        'Syria' => 'Syria',
        'Taiwan' => 'Taiwan',
        'Tajikistan' => 'Tajikistan',
        'Tanzania' => 'Tanzania',
        'Thailand' => 'Thailand',
        'Togo' => 'Togo',
        'Tonga' => 'Tonga',
        'Trinidad and Tobago' => 'Trinidad and Tobago',
        'Tunisia' => 'Tunisia',
        'Turkey' => 'Turkey',
        'Turkmenistan' => 'Turkmenistan',
        'Tuvalu' => 'Tuvalu',
        'Uganda' => 'Uganda',
        'Ukraine' => 'Ukraine',
        'United Arab Emirates' => 'United Arab Emirates',
        'Uruguay' => 'Uruguay',
        'Uzbekistan' => 'Uzbekistan',
        'Vanuatu' => 'Vanuatu',
        'Vatican City (Holy See)' => 'Vatican City (Holy See)',
        'Venezuela' => 'Venezuela',
        'Vietnam' => 'Vietnam',
        'Yemen' => 'Yemen',
        'Zambia' => 'Zambia',
        'Zimbabwe' => 'Zimbabwe',
    ];

    public const PRACTICE_LICENSING_BODY_SELECT = [
        'AHPRA' => 'AHPRA',
        'GMC' => 'GMC',
    ];

    public const EXPERIENCE_FROM_RESIDING_SELECT = [
        '1-3' => '1-3',
        '3-5' => '3-5',
        '5-10' => '5-10',
        'Above 10' => 'Above 10',
    ];

    public const CURRENT_EMPLOYMENT_STATUS_SELECT = [
        'Employed' => 'Employed',
        'Non-employed' => 'Non-employed',
        'Student' => 'Student',
        'Paternity Break' => 'Paternity Break',
        'Maternity Break' => 'Maternity Break',
        'Redundant' => 'Redundant',
        'Phase of Career Break' => 'Phase of Career Break',
    ];

    public const COUNTRY_OF_PRIMARY_DEGREE_SELECT = [
        'Australia ' => 'Australia ',
        'New Zealand' => 'New Zealand',
        'United Kingdom ' => 'United Kingdom ',
        'Austria  ' => 'Austria  ',
        'Belgium' => 'Belgium',
        'Canada ' => 'Canada ',
        'Czech Republic  ' => 'Czech Republic  ',
        'Denmark  ' => 'Denmark  ',
        'Finland  ' => 'Finland  ',
        'France ' => 'France ',
        'Germany  ' => 'Germany  ',
        'Greece' => 'Greece',
        'Iceland ' => 'Iceland ',
        'Israel  ' => 'Israel  ',
        'Italy ' => 'Italy ',
        'Norway ' => 'Norway ',
        'Portugal  ' => 'Portugal  ',
        'Republic of Ireland  ' => 'Republic of Ireland  ',
        'Singapore  ' => 'Singapore  ',
        'Spain ' => 'Spain ',
        'Sweden ' => 'Sweden ',
        'Switzerland ' => 'Switzerland ',
        'The Netherlands ' => 'The Netherlands ',
        'United States of America ' => 'United States of America ',
        'Afghanistan' => 'Afghanistan',
        'Albania' => 'Albania',
        'Algeria' => 'Algeria',
        'Andorra' => 'Andorra',
        'Angola' => 'Angola',
        'Antigua and Barbuda' => 'Antigua and Barbuda',
        'Argentina' => 'Argentina',
        'Armenia' => 'Armenia',
        'Azerbaijan' => 'Azerbaijan',
        'The Bahamas' => 'The Bahamas',
        'Bahrain' => 'Bahrain',
        'Bangladesh' => 'Bangladesh',
        'Barbados' => 'Barbados',
        'Belarus' => 'Belarus',
        'Belize' => 'Belize',
        'Benin' => 'Benin',
        'Bhutan' => 'Bhutan',
        'Bolivia' => 'Bolivia',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
        'Botswana' => 'Botswana',
        'Brazil' => 'Brazil',
        'Brunei' => 'Brunei',
        'Bulgaria' => 'Bulgaria',
        'Burkina Faso' => 'Burkina Faso',
        'Burundi' => 'Burundi',
        'Cambodia' => 'Cambodia',
        'Cameroon' => 'Cameroon',
        'Cape Verde' => 'Cape Verde',
        'Central African Republic' => 'Central African Republic',
        'Chad' => 'Chad',
        'Chile' => 'Chile',
        'China' => 'China',
        'Colombia' => 'Colombia',
        'Comoros' => 'Comoros',
        'Congo, Republic of the' => 'Congo, Republic of the',
        'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
        'Costa Rica' => 'Costa Rica',
        'Cote d-Ivoire' => 'Cote d-Ivoire',
        'Croatia' => 'Croatia',
        'Cuba' => 'Cuba',
        'Cyprus' => 'Cyprus',
        'Djibouti' => 'Djibouti',
        'Dominica' => 'Dominica',
        'Dominican Republic' => 'Dominican Republic',
        'East Timor (Timor-Leste)' => 'East Timor (Timor-Leste)',
        'Ecuador' => 'Ecuador',
        'Egypt' => 'Egypt',
        'El Salvador' => 'El Salvador',
        'Equatorial Guinea' => 'Equatorial Guinea',
        'Eritrea' => 'Eritrea',
        'Estonia' => 'Estonia',
        'Ethiopia' => 'Ethiopia',
        'Fiji' => 'Fiji',
        'Gabon' => 'Gabon',
        'The Gambia' => 'The Gambia',
        'Georgia' => 'Georgia',
        'Ghana' => 'Ghana',
        'Grenada' => 'Grenada',
        'Guatemala' => 'Guatemala',
        'Guinea' => 'Guinea',
        'Guinea-Bissau' => 'Guinea-Bissau',
        'Guyana' => 'Guyana',
        'Haiti' => 'Haiti',
        'Honduras' => 'Honduras',
        'Hungary' => 'Hungary',
        'India' => 'India',
        'Indonesia' => 'Indonesia',
        'Iran' => 'Iran',
        'Iraq' => 'Iraq',
        'Ireland' => 'Ireland',
        'Jamaica' => 'Jamaica',
        'Japan' => 'Japan',
        'Jordan' => 'Jordan',
        'Kazakhstan' => 'Kazakhstan',
        'Kenya' => 'Kenya',
        'Kiribati' => 'Kiribati',
        'Korea, North' => 'Korea, North',
        'Korea, South' => 'Korea, South',
        'Kosovo' => 'Kosovo',
        'Kuwait' => 'Kuwait',
        'Kyrgyzstan' => 'Kyrgyzstan',
        'Laos' => 'Laos',
        'Latvia' => 'Latvia',
        'Lebanon' => 'Lebanon',
        'Lesotho' => 'Lesotho',
        'Liberia' => 'Liberia',
        'Libya' => 'Libya',
        'Liechtenstein' => 'Liechtenstein',
        'Lithuania' => 'Lithuania',
        'Luxembourg' => 'Luxembourg',
        'Macedonia' => 'Macedonia',
        'Madagascar' => 'Madagascar',
        'Malawi' => 'Malawi',
        'Malaysia' => 'Malaysia',
        'Maldives' => 'Maldives',
        'Mali' => 'Mali',
        'Malta' => 'Malta',
        'Marshall Islands' => 'Marshall Islands',
        'Mauritania' => 'Mauritania',
        'Mauritius' => 'Mauritius',
        'Mexico' => 'Mexico',
        'Micronesia, Federated States of' => 'Micronesia, Federated States of',
        'Moldova' => 'Moldova',
        'Monaco' => 'Monaco',
        'Mongolia' => 'Mongolia',
        'Montenegro' => 'Montenegro',
        'Morocco' => 'Morocco',
        'Mozambique' => 'Mozambique',
        'Myanmar (Burma)' => 'Myanmar (Burma)',
        'Namibia' => 'Namibia',
        'Nauru' => 'Nauru',
        'Nepal' => 'Nepal',
        'Nicaragua' => 'Nicaragua',
        'Niger' => 'Niger',
        'Nigeria' => 'Nigeria',
        'Oman' => 'Oman',
        'Pakistan' => 'Pakistan',
        'Palau' => 'Palau',
        'Panama' => 'Panama',
        'Papua New Guinea' => 'Papua New Guinea',
        'Paraguay' => 'Paraguay',
        'Peru' => 'Peru',
        'Philippines' => 'Philippines',
        'Poland' => 'Poland',
        'Qatar' => 'Qatar',
        'Romania' => 'Romania',
        'Russia' => 'Russia',
        'Rwanda' => 'Rwanda',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
        'Saint Lucia' => 'Saint Lucia',
        'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
        'Samoa' => 'Samoa',
        'San Marino' => 'San Marino',
        'Sao Tome and Principe' => 'Sao Tome and Principe',
        'Saudi Arabia' => 'Saudi Arabia',
        'Senegal' => 'Senegal',
        'Serbia' => 'Serbia',
        'Seychelles' => 'Seychelles',
        'Sierra Leone' => 'Sierra Leone',
        'Slovakia' => 'Slovakia',
        'Slovenia' => 'Slovenia',
        'Solomon Islands' => 'Solomon Islands',
        'Somalia' => 'Somalia',
        'South Africa' => 'South Africa',
        'South Sudan' => 'South Sudan',
        'Sri Lanka' => 'Sri Lanka',
        'Sudan' => 'Sudan',
        'Suriname' => 'Suriname',
        'Swaziland' => 'Swaziland',
        'Syria' => 'Syria',
        'Taiwan' => 'Taiwan',
        'Tajikistan' => 'Tajikistan',
        'Tanzania' => 'Tanzania',
        'Thailand' => 'Thailand',
        'Togo' => 'Togo',
        'Tonga' => 'Tonga',
        'Trinidad and Tobago' => 'Trinidad and Tobago',
        'Tunisia' => 'Tunisia',
        'Turkey' => 'Turkey',
        'Turkmenistan' => 'Turkmenistan',
        'Tuvalu' => 'Tuvalu',
        'Uganda' => 'Uganda',
        'Ukraine' => 'Ukraine',
        'United Arab Emirates' => 'United Arab Emirates',
        'Uruguay' => 'Uruguay',
        'Uzbekistan' => 'Uzbekistan',
        'Vanuatu' => 'Vanuatu',
        'Vatican City (Holy See)' => 'Vatican City (Holy See)',
        'Venezuela' => 'Venezuela',
        'Vietnam' => 'Vietnam',
        'Yemen' => 'Yemen',
        'Zambia' => 'Zambia',
        'Zimbabwe' => 'Zimbabwe',
    ];

    public const PROFESSIONAL_QUALIFICATION_SELECT = [
        'abc' => 'abc',
    ];

    public const RECOGNISED_COMPARABLE_EXPERIENCE_SELECT = [
        '1-3' => '1-3',
        '3-5' => '3-5',
        '5-10' => '5-10',
        'Above 10' => 'Above 10',
    ];

    public const GENDER_SELECT = [

        'Male'   => 'Male',
        'Female' => 'Female',
    ];

    public const TITLE_SELECT = [

        'Mr' => 'Mr',
        'Mrs' => 'Mrs',
        'Miss' => 'Miss',
        'Ms' => 'Ms',
        'Dr' => 'Dr',
        'Prof' => 'Prof',
        'Other' => 'Other',
    ];

    public $table = 'candidates';

    protected $hidden = [
        'password',
    ];

    protected $dates = [
        'dob',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $appends = [
        'cv_document',
        'registration_form_document',
        'privacy_concerns',
    ];

    protected $fillable = [
        'title',
        'user_id',
        'first_name',
        'last_name',
        'gender',
        'dob',
        'mobile',
        'home',
        'work',
        'email',
        'address_1',
        'address_2',
        'distance_to_main',
        'town',
        'state',
        'district',
        'country',
        'post_code',
        'main_city',
        'profession',
        'devision',
        'senority',
        'specialty',
        'professional_qualification',
        'graduation',
        'country_of_primary_degree',
        'medical_school',
        'practice_country',
        'practice_licensing_body',
        'license_type',
        'experience_from_home',
        'experience_from_residing',
        'recognised_comparable_experience',
        'current_employment_status',
        'country_of_citizenship',
        'country_of_residence',
        'visa_type',
        'work_rights_status',
        'profession_login',
        'username',
        'password',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    public function getDobAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setDobAttribute($value)
    {
        $this->attributes['dob'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }

    // public function getCvDocumentAttribute()
    // {
    //     return $this->getMedia('cv_document')->last();
    // }

    // public function getRegistrationFormDocumentAttribute()
    // {
    //     return $this->getMedia('registration_form_document')->last();
    // }

    // public function getPrivacyConcernsAttribute()
    // {
    //     return $this->getMedia('privacy_concerns')->last();
    // }
    public function candidate_profile()
    {
        return $this->belongsTo(CandidateProfile::class,'id','candidate_id');
    }
    public function interview()
    {
        return $this->belongsTo(Interview::class,'id','candidate_id');
    }

    public function progbar()
    {
        return $this->belongsTo(Progbar::class,'id','candidate_id');
    }

    public function activebar()
    {
        return $this->belongsTo(Activebar::class,'id','candidate_id');
    }

    public function assignbar()
    {
        return $this->belongsTo(Assignbar::class,'id','candidate_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}
